/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#8cf3f3",
        "tertiary": "#005412",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#424752",
        "secondary-fixed-dim": "#6fd7d6",
        "primary": "#00478d",
        "surface-container": "#edeeef",
        "surface-tint": "#005db6",
        "outline-variant": "#c2c6d4",
        "on-secondary-fixed": "#002020",
        "error-container": "#ffdad6",
        "outline": "#727783",
        "on-primary": "#ffffff",
        "tertiary-fixed": "#a3f69c",
        "error": "#ba1a1a",
        "surface-container-high": "#e7e8e9",
        "on-error": "#ffffff",
        "background": "#f8f9fa",
        "inverse-surface": "#2e3132",
        "secondary-fixed": "#8cf3f3",
        "surface-container-low": "#f3f4f5",
        "primary-fixed-dim": "#a9c7ff",
        "secondary": "#006a6a",
        "on-tertiary-container": "#9bee94",
        "surface-bright": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "on-primary-fixed": "#001b3d",
        "surface": "#f8f9fa",
        "on-error-container": "#93000a",
        "on-primary-container": "#c8daff",
        "tertiary-container": "#1d6e25",
        "on-secondary-fixed-variant": "#004f4f",
        "on-secondary-container": "#007070",
        "on-secondary": "#ffffff",
        "primary-container": "#005eb8",
        "tertiary-fixed-dim": "#88d982",
        "inverse-primary": "#a9c7ff",
        "on-primary-fixed-variant": "#00468c",
        "surface-container-highest": "#e1e3e4",
        "surface-dim": "#d9dadb",
        "on-surface": "#191c1d",
        "primary-fixed": "#d6e3ff",
        "on-tertiary-fixed-variant": "#005312",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed": "#002204",
        "on-background": "#191c1d",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
